name: build-and-release

on:
  workflow_dispatch:
  push:
    branches: [ main ]

# Grant write permissions so the workflow can create Git tags
permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore certificate-creator.sln

      - name: Publish WPF application
        run: dotnet publish src/CertificateCreator/CertificateCreator.csproj -c Release -r win-x64 --self-contained false -o publish

      - name: Archive WPF binaries
        run: Compress-Archive -Path publish/* -DestinationPath certificate-creator.zip

      - name: Publish CLI for linux
        run: dotnet publish src/CertificateCli/CertificateCli.csproj -c Release -r linux-x64 --self-contained false -o publish-cli-linux

      - name: Archive CLI linux
        run: Compress-Archive -Path publish-cli-linux/* -DestinationPath certificate-cli-linux.zip

      - name: Publish CLI for macOS
        run: dotnet publish src/CertificateCli/CertificateCli.csproj -c Release -r osx-x64 --self-contained false -o publish-cli-osx

      - name: Archive CLI macOS
        run: Compress-Archive -Path publish-cli-osx/* -DestinationPath certificate-cli-osx.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: |
            certificate-creator.zip
            certificate-cli-linux.zip
            certificate-cli-osx.zip
          name: certificate-binaries

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: certificate-binaries
          path: .

      - name: Bump version and create tag
        id: tag
        uses: anothrNick/github-tag-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch

      - name: Create GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            certificate-creator.zip
            certificate-cli-linux.zip
            certificate-cli-osx.zip
          tag: ${{ steps.tag.outputs.new_tag }}
          token: ${{ secrets.GITHUB_TOKEN }}
          generate_release_notes: true
